### ISSUE TITLE
Add ability to "pin" docker versions

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-up#11]
**Is your feature request related to a problem? Please describe.**
Right now `senzing-up.sh` grabs the `:latest` docker images.
In reality it should retrieve a `source` file from this repository to set enviroment variables used to pin docker images.  Then in `senzing-up.sh` the use of Docker would be something like this:

```
:
    sudo docker pull senzing/web-app-demo:${SENZING_WEB_APP_DEMO_VERSION}
:
sudo docker run \
    --publish ${WEB_APP_PORT}:8251 \
    --rm \
    --user $(id -u):$(id -g) \
    --volume ${SENZING_DATA_DIR}:/opt/senzing/data \
    --volume ${SENZING_ETC_DIR}:/etc/opt/senzing \
    --volume ${SENZING_G2_DIR}:/opt/senzing/g2 \
    --volume ${SENZING_VAR_DIR}:/var/opt/senzing \
    senzing/web-app-demo:${SENZING_WEB_APP_DEMO_VERSION}
```

**Comment by docktermj** [comment]
The source file would be retrieved when a customer first installs or requests an update.

This would prevent breakage if there is something bad in master/latest.   Or if a particular ensemble of containers don't work together.

**Comment by docktermj** [comment]
Initial fix via https://github.com/Senzing/senzing-up/issues/34

**Comment by kernelsam** [comment]
Closing as will not be implemented due to deprecation.
