### ISSUE TITLE
Migrate to senzing/stream-producer

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-up#14]
**Is your feature request related to a problem? Please describe.**
With [senzing/stream-producer](https://github.com/Senzing/stream-producer) deprecating [senzing/mock-data-generator](https://github.com/Senzing/mock-data-generator), a new `docker-bin/senzing-stream-producer.sh` needs to replace `docker-bin/senzing-mock-data-generator.sh`

See https://github.com/Senzing/stream-producer/issues/3

**Comment by docktermj** [comment]
Reference: https://github.com/Senzing/mock-data-generator/issues/44

**Comment by SamMacy** [comment]
[This line](https://github.com/Senzing/senzing-up/blob/096bb4a1bb1fa3978c4c73170674337a28f753c8/senzing-up.sh#L372) makes the reference to Senzing/mock-data-generator, nothing direct.
