### ISSUE TITLE
Integrate DB2 docker-compose with Senzing-up web app

### ISSUE THREAD

**Issue by edykes** [Senzing/senzing-up#32]
During our debug session on RHEL 7.8, we found that there were issues with the web app docker in the Senzing-up deployment not seeing the API-server in the same deployment, after it was configured to use the DB2 docker in the  docker-compose formation.  A possible work-around that I found, which I've tested successfully is to add the following to the web-app docker, with the assumption that it must start after the api-server.

export SENZING_API_SERVER_NAME=${SENZING_PROJECT_NAME}-api-server
    export SENZING_API_SERVER_URL="http:\\\\"$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${SENZING_API_SERVER_NAME}):${SENZING_DOCKER_PORT_SENZING_API_SERVER}

A screen print of this was sent direct to Michael.

**Comment by docktermj** [comment]
@edykes We're going through a prioritization exercise.  Is this something that is needed in the next 3 months?

**Comment by edykes** [comment]
At this time I would say no since we have a work-around.  If anything
changes, I'll let you know.
