### ISSUE TITLE
Search record by special field

### ISSUE THREAD

**Issue by navjeetc** [Senzing/senzing-up#40]
**Describe the bug/issue**
How do I search the data for a custom field (RECORD_ID and/or AGENCY_ID in my case)

**To Reproduce**

Sample data:
```
AGENCY_ID,RECORD_ID,PRIMARY_NAME_LAST,PRIMARY_NAME_FIRST,PRIMARY_NAME_MIDDLE,GENDER,DATE_OF_BIRTH,SSN_NUMBER,HOME_ADDR_LINE1,HOME_ADDR_CITY,HOME_ADDR_STATE,HOME_ADDR_POSTAL_CODE,WORK_PHONE_NUMBER
FFEMS,130831004,Jones,Elizabeth,R,F,2/2/2002,322-22-2222,111 First St,San Mateo,VA,22004,
FFEMS,130831005,Sheehan,Jamie,H,M,4/13/2007,189-50-0966,2280 Stoney Lonesome Road,Pittston,VA,22001,703-300-5826
```
**So I would like find a record where RECORD is 130831004
Also I would like find records where  AGENCY_ID is FFEMS and full name is 'John Doe'**

Just to show you, loading of data in TEST mode gives this output:

Testing /var/opt/senzing/jp.csv, CTRL-C to end test at any time...

  Dropping to single thread due to small file size

Statistics
----------

    Start time:                     06:14:52pm
    End time:                       06:14:52pm
    File loaded:                    /var/opt/senzing/jp.csv
    Shuffled into:                  Shuffled file deleted (-nsd to keep after load)
    Good records:                   53
    Bad records:                    0
    Incomplete records:             0
    Total elapsed time:             0.0 mins
    Time processing redo:           Redo disabled (-n)
    Time paused in governor(s):     0.0 mins
    Records per second:             11805

 Features:
  NAME-PRIMARY .......... 53           (100.0%)
  GENDER ................ 53           (100.0%)
  DOB ................... 52           (98.11%)
  SSN ................... 53           (100.0%)
  ADDRESS-HOME .......... 53           (100.0%)
  PHONE-WORK ............ 50           (94.34%)
 Unmapped:
  AGENCY_ID ............. 53           (100.0%)

**Expected behavior**
Search records by RECORD_ID and/or AGENCY_ID 

 
**Desktop (please complete the following information):**

- OS: MacOS

**Comment by docktermj** [comment]
@navjeetc For information on how to use Senzing,  I'll direct you to a different help desk.   Please send an email to support@senzing.com

**Comment by docktermj** [comment]
@navjeetc I see you have submitted to support@senzing.com (Ticket #3472).    We'll take care of you there.

If there is something blocking you in this specific repository, please let us know.   If not, please close this issue.  If I don't hear anything within 7 days, I'll go ahead and close this issue.

**Comment by docktermj** [comment]
Didn't hear back from originator.  Closing issue
